name: "Build image with Notification"

on:
  workflow_call:
    inputs:
      images:
        description: "Docker image to build"
        required: true
        type: string
      tags:
        description: "Docker image tags"
        required: true
        type: string
      labels:
        description: "Docker image labels"
        required: false
        type: string
        default: ""
      context:
        description: "Docker context"
        required: false
        type: string
        default: "."
      file:
        description: "Dockerfile"
        required: false
        type: string
        default: "Dockerfile"
      push:
        description: "Push Docker image"
        required: false
        type: boolean
        default: false
      platforms:
        description: "Docker platforms, e.g. linux/amd64,linux/arm64"
        required: false
        type: string
        default: "linux/amd64,linux/arm64"
      meta_labels:
        description: "Docker image labels on metadata"
        required: false
        type: string

    secrets:
      DOCKERHUB_USERNAME:
        description: "Docker Hub username"
        required: true
      DOCKERHUB_TOKEN:
        description: "Docker Hub token"
        required: true
      TOKEN:
        description: "GitHub token"
        required: true
      BOT_TOKEN:
        description: "Telegram bot token"
        required: false
      CHAT_ID:
        description: "Telegram chat ID"
        required: false
      REPLY_TO_MESSAGE_ID:
        description: "Telegram reply to message ID, means the topic id"
        required: false

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print inputs
        run: |
          echo -e "images:\n${{ inputs.images }}"
          echo -e "tags:\n${{ inputs.tags }}"
          echo -e "labels:\n${{ inputs.labels }}"
          echo -e "context:\n${{ inputs.context }}"
          echo -e "file:\n${{ inputs.file }}"
          echo -e "push:\n${{ inputs.push }}"
          echo -e "platforms:\n${{ inputs.platforms }}"
          echo -e "meta_labels:\n${{ inputs.meta_labels }}"

      - name: Prepare
        id: prep
        run: |
          echo "start_time=$(date +%s)" >> $GITHUB_OUTPUT
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ" -d '8 hour')
          echo "timestamp=$timestamp" >> $GITHUB_OUTPUT
          # Test readme file exist
          readme_path="${{ inputs.context }}/README.md"
          if [ ! -f "$readme_path" ]; then
            echo "README.md not found in $readme_path"
            echo "readme_path=''" >> $GITHUB_OUTPUT
          else
            echo "readme_path=$readme_path" >> $GITHUB_OUTPUT
          fi
          # Get username/repo from images
          images=$(echo "${{ inputs.images }}" | tr ',' '\n')
          for image in $images; do
            if [[ $image =~ ^aliuq/.+ ]]; then
              echo "repo=$image" >> $GITHUB_OUTPUT
            fi
          done

      - name: Docker meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ inputs.images }}
          tags: ${{ inputs.tags }}
          labels: ${{ inputs.meta_labels }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Build and push Docker images
      #   uses: docker/build-push-action@v6
      #   id: build
      #   with:
      #     context: ${{ inputs.context }}
      #     file: ${{ inputs.file }}
      #     platforms: ${{ inputs.platforms }}
      #     push: ${{ inputs.push }}
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: |
      #       ${{ steps.meta.outputs.labels }}
      #       ${{ inputs.labels }}

      # - name: Update README
      #   uses: peter-evans/dockerhub-description@v4
      #   if: steps.prep.outputs.readme_path != '' && inputs.push == true && steps.prep.outputs.repo != ''
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     repository: ${{ steps.prep.outputs.repo }}
      #     readme-filepath: ${{ steps.prep.outputs.readme_path }}

      - name: Test
        if: steps.prep.outputs.readme_path != '' && inputs.push == true && steps.prep.outputs.repo != ''
        run: |
          echo "readme_path: ${{ steps.prep.outputs.readme_path }}"

      - name: End timer
        id: post_prep
        run: |
          END_TIME=$(date +%s)
          START_TIME=${{ steps.prep.outputs.start_time }}
          DURATION=$((END_TIME - START_TIME))
          echo "duration=$DURATION" >> $GITHUB_OUTPUT

          TAGS=$(echo '${{ steps.meta.outputs.tags }}' | \
            while IFS= read -r line; do \
              echo "\`$line\`"; \
            done)
          echo "tags<<EOF" >> $GITHUB_OUTPUT
          echo "$TAGS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "readme_path: ${{ steps.prep.outputs.readme_path }}"

      # - name: Notify
      #   uses: aliuq/telegram-action@v1
      #   if: env.BOT_TOKEN && env.CHAT_ID
      #   env:
      #     BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      #     CHAT_ID: ${{ secrets.CHAT_ID }}
      #   with:
      #     bot_token: ${{ secrets.BOT_TOKEN }}
      #     chat_id: ${{ secrets.CHAT_ID }}
      #     reply_to_message_id: ${{ secrets.REPLY_TO_MESSAGE_ID }}
      #     message: |
      #       🎉 **Docker Image Build Notification**

      #       **Repository**: [${{ github.repository }}](https://github.com/${{ github.repository }})

      #       **Tags**:
      #       ${{ steps.post_prep.outputs.tags }}

      #       **Platforms**: `${{ inputs.platforms || 'linux/amd64' }}`
      #       **BuildTime**: `${{ steps.prep.outputs.timestamp }}`
      #       **BuildDuration**: `${{ steps.post_prep.outputs.duration }}s`

      #       [**View Action**](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

      #       #build_image_notify
