name: 'Upstream Sync'

on:
  workflow_call:
    inputs:
      ref:
        description: 'Branch to checkout, [see more](https://github.com/aormsby/Fork-Sync-With-Upstream-action)'
        required: false
        default: 'master'
        type: string
      persist-credentials:
        description: 'REQUIRED if your upstream repo is private (see wiki) [see more](https://github.com/aormsby/Fork-Sync-With-Upstream-action)'
        required: false
        default: false
        type: boolean
      target_sync_branch:
        description: 'Branch to sync, defaults to `ref`'
        required: false
        type: string
      upstream_sync_branch:
        description: 'Branch to sync from, defaults to `master`'
        required: false
        default: 'master'
        type: string
      upstream_sync_repo:
        description: 'Repo to sync from'
        required: true
        type: string
      sync_test_mode:
        description: 'Fork Sync Test Mode, defaults to `false`'
        required: false
        default: false
        type: boolean
    secrets:
      token:
        description: 'GitHub Token'
        required: true
      upstream_repo_secret:
        required: false

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        persist-credentials: ${{ inputs.persist-credentials }}
      
    - name: Echo All Inputs and Secrets
      run: |
        echo "Checkout Branch: ${{ inputs.ref }}"
        echo "Check Persist Credentials: ${{ inputs.persist-credentials }}"
        echo "Target Sync Branch: ${{ inputs.target_sync_branch || inputs.ref }}"
        echo "Upstream Sync Branch: ${{ inputs.upstream_sync_branch }}"
        echo "Upstream Sync Repo: ${{ inputs.upstream_sync_repo }}"
        echo "Sync Test Mode: ${{ inputs.sync_test_mode }}"
        echo "GITHUB_TOKEN: ${{ secrets.token }}"
        echo "upstream_repo_secret: ${{ secrets.upstream_repo_secret }}"

    # - name: Sync upstream changes
    #   id: sync
    #   uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
    #   with:
    #     target_sync_branch: ${{ inputs.target_sync_branch }}
    #     target_repo_token: ${{ secrets.token }}
    #     upstream_sync_branch: ${{ inputs.upstream_sync_branch }}
    #     upstream_sync_repo: ${{ inputs.upstream_sync_repo }}
    #     upstream_repo_access_token: ${{ secrets.upstream_repo_secret }}
    #     test_mode: ${{ inputs.sync_test_mode }}

    # - name: New commits found
    #   if: steps.sync.outputs.has_new_commits == 'true'
    #   run: echo "New commits were found to sync."

    # - name: No new commits found
    #   if: steps.sync.outputs.has_new_commits == 'false'
    #   run: echo "There were no new commits."

    # - name: Show value of 'has_new_commits'
    #   run: echo ${{ steps.sync.outputs.has_new_commits }}
