name: 'Upstream Sync'

on:
  workflow_call:
    inputs:
      checkout_branch:
        description: 'Branch to checkout'
        required: false
        default: 'main'
        type: string
      check_persist_credentials:
        description: 'Persist credentials'
        required: false
        default: 'false'
        type: boolean
      target_sync_branch:
        description: 'Branch to sync'
        required: false
        default: ${{ inputs.checkout_branch }}
        type: string
      upstream_sync_branch:
        description: 'Branch to sync from'
        required: true
        default: 'main'
        type: string
      upstream_sync_repo:
        description: 'Repo to sync from'
        required: true
        type: string
      sync_test_mode:
        description: 'Fork Sync Test Mode'
        required: false
        default: false
        type: boolean
    secrets:
      GITHUB_TOKEN:
        required: true
      UPSTREAM_REPO_SECRET:
        required: false

  workflow_dispatch:  # click the button on Github repo!
    inputs:
      sync_test_mode: # Adds a boolean option that appears during manual workflow run for easy test mode config
        description: 'Fork Sync Test Mode'
        type: boolean
        default: false

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:
    - name: Checkout target repo
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.checkout_branch }}
        persist-credentials: ${{ inputs.check_persist_credentials }}
      
    - name: Echo All Inputs and Secrets
      run: |
        echo "Checkout Branch: ${{ inputs.checkout_branch }}"
        echo "Check Persist Credentials: ${{ inputs.check_persist_credentials }}"
        echo "Target Sync Branch: ${{ inputs.target_sync_branch }}"
        echo "Upstream Sync Branch: ${{ inputs.upstream_sync_branch }}"
        echo "Upstream Sync Repo: ${{ inputs.upstream_sync_repo }}"
        echo "Sync Test Mode: ${{ inputs.sync_test_mode }}"
        echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
        echo "UPSTREAM_REPO_SECRET: ${{ secrets.UPSTREAM_REPO_SECRET }}"

    # - name: Sync upstream changes
    #   id: sync
    #   uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
    #   with:
    #     target_sync_branch: ${{ inputs.target_sync_branch }}
    #     target_repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     upstream_sync_branch: ${{ inputs.upstream_sync_branch }}
    #     upstream_sync_repo: ${{ inputs.upstream_sync_repo }}
    #     upstream_repo_access_token: ${{ secrets.UPSTREAM_REPO_SECRET }}
    #     test_mode: ${{ inputs.sync_test_mode }}

    # - name: New commits found
    #   if: steps.sync.outputs.has_new_commits == 'true'
    #   run: echo "New commits were found to sync."

    # - name: No new commits found
    #   if: steps.sync.outputs.has_new_commits == 'false'
    #   run: echo "There were no new commits."

    # - name: Show value of 'has_new_commits'
    #   run: echo ${{ steps.sync.outputs.has_new_commits }}
