name: 'Upstream Sync'

on:
  workflow_call:
    inputs:
      ref:
        description: 'Branch to checkout, [see more](https://github.com/aormsby/Fork-Sync-With-Upstream-action)'
        required: false
        default: 'master'
        type: string
      persist-credentials:
        description: 'REQUIRED if your upstream repo is private (see wiki) [see more](https://github.com/aormsby/Fork-Sync-With-Upstream-action)'
        required: false
        default: false
        type: boolean
      target_sync_branch:
        description: 'Branch to sync, defaults to `ref`'
        required: false
        type: string
      upstream_sync_branch:
        description: 'Branch to sync from, defaults to `master`'
        required: false
        default: 'master'
        type: string
      upstream_sync_repo:
        description: 'Repo to sync from'
        required: true
        type: string
      sync_test_mode:
        description: 'Fork Sync Test Mode, defaults to `false`'
        required: false
        default: false
        type: boolean
      show_output:
        description: 'Show output of `has_new_commits`, defaults to `true`'
        required: false
        default: true
        type: boolean
      debug:
        description: 'Debug mode, defaults to `false`'
        required: false
        default: 'false'
        type: string
    secrets:
      token:
        description: 'GitHub Token'
        required: true
      upstream_repo_secret:
        required: false
    outputs:
      has_new_commits:
        description: 'New commits found'
        value: ${{ jobs.sync_latest_from_upstream.outputs.has_new_commits }}

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    outputs:
      has_new_commits: ${{ steps.sync.outputs.has_new_commits }}

    steps:
    - name: Echo all inputs
      # if: ${{ inputs.debug }}
      run: |
        echo "debug: ${{ inputs.debug }}"
        echo "ref: ${{ inputs.ref }}"
        echo "persist-credentials: ${{ inputs.persist-credentials }}"
        echo "target_sync_branch: ${{ inputs.target_sync_branch }}"
        echo "upstream_sync_branch: ${{ inputs.upstream_sync_branch }}"
        echo "upstream_sync_repo: ${{ inputs.upstream_sync_repo }}"
        echo "sync_test_mode: ${{ inputs.sync_test_mode }}"
        echo "show_output: ${{ inputs.show_output }}"
        echo "token: ${{ secrets.token }}"
        echo "upstream_repo_secret: ${{ secrets.upstream_repo_secret }}"
        # Mock the github actions output success
        exit 0
        
    # - name: Checkout target repo
    #   uses: actions/checkout@v4
    #   with:
    #     ref: ${{ inputs.ref }}
    #     persist-credentials: ${{ inputs.persist-credentials }}

    # - name: Sync upstream changes
    #   id: sync
    #   uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
    #   with:
    #     target_sync_branch: ${{ inputs.target_sync_branch || inputs.ref }}
    #     target_repo_token: ${{ secrets.token }}
    #     upstream_sync_branch: ${{ inputs.upstream_sync_branch }}
    #     upstream_sync_repo: ${{ inputs.upstream_sync_repo }}
    #     upstream_repo_access_token: ${{ secrets.upstream_repo_secret }}
    #     test_mode: ${{ inputs.sync_test_mode }}

    # - name: New commits found
    #   if: steps.sync.outputs.has_new_commits == 'true' && inputs.show_output
    #   run: echo "New commits were found to sync."

    # - name: No new commits found
    #   if: steps.sync.outputs.has_new_commits == 'false' && inputs.show_output
    #   run: echo "There were no new commits."

