name: "Telegram Notification"

on:
  workflow_call:
    inputs:
      text:
        description: "Telegram message text"
        required: true
        type: "string"
    secrets:
      BOT_TOKEN:
        description: "Telegram Bot Token"
        required: true
      CHAT_ID:
        description: "Telegram chat id"
        required: true
      REPLY_TO_MESSAGE_ID:
        description: "Telegram reply to message id"
        required: false

jobs:
  send_telegram_message:
    name: Send Telegram message
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          REPLY_TO_MESSAGE_ID: ${{ secrets.REPLY_TO_MESSAGE_ID }}
          TEXT: ${{ inputs.text }}
        run: |
          # Telegram API 基本信息
          base_url="https://api.telegram.org/bot$BOT_TOKEN/sendMessage"
          action_url="https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"

          # 获取仓库名称，并将中线替换为下划线
          repo_name=$(echo "${GITHUB_REPOSITORY}" | awk -F'/' '{print $NF}' | sed 's/-/_/g')

          # 基本参数
          params="chat_id=$CHAT_ID&parse_mode=MarkdownV2&disable_web_page_preview=true"

          # 如果有回复消息的 ID，添加到参数中
          if [[ -n "$REPLY_TO_MESSAGE_ID" ]]; then
            params+="&reply_to_message_id=$REPLY_TO_MESSAGE_ID"
          fi

          # 添加消息文本
          params+="&text=$(echo -e "$TEXT")"

          # 输出调试信息（可选）
          echo "curl -s -X POST \"$base_url\" -d \"$params\""

          # 使用 curl 发送请求
          # curl -s -X POST "$base_url" -d "$params"
