name: Build image with Notification(Test)

on:
  workflow_call:
    inputs:
      images:
        description: "Docker image to build"
        required: true
        type: string
      tags:
        description: "Docker image tags"
        required: true
        type: string
      labels:
        description: "Docker image labels"
        required: false
        type: string
        default: ""
      context:
        description: "Docker context"
        required: false
        type: string
        default: "."
      file:
        description: "Dockerfile"
        required: false
        type: string
        default: "Dockerfile"
      push:
        description: "Push Docker image"
        required: false
        type: boolean
        default: false
      platforms:
        description: "Docker platforms, e.g. linux/amd64,linux/arm64"
        required: false
        type: string
        default: "linux/amd64,linux/arm64"
      meta_labels:
        description: "Docker image labels on metadata"
        required: false
        type: string
      annotations:
        description: "Docker image annotations"
        required: false
        type: string
      notify:
        description: "Notify"
        required: false
        type: boolean
        default: true
      readme_path:
        description: "Readme file path"
        required: false
        type: string

    secrets:
      DOCKERHUB_USERNAME:
        description: "Docker Hub username"
        required: true
      DOCKERHUB_TOKEN:
        description: "Docker Hub token"
        required: true
      TOKEN:
        description: "GitHub token"
        required: true
      BOT_TOKEN:
        description: "Telegram bot token"
        required: false
      CHAT_ID:
        description: "Telegram chat ID"
        required: false
      REPLY_TO_MESSAGE_ID:
        description: "Telegram reply to message ID, means the topic id"
        required: false

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print inputs
        run: |
          echo -e "\033[36m#images\033[39m:\n${{ inputs.images }}"
          echo -e "\033[36m#tags\033[39m:\n${{ inputs.tags }}"
          echo -e "\033[36m#labels\033[39m:\n${{ inputs.labels }}"
          echo -e "\033[36m#context\033[39m: ${{ inputs.context }}"
          echo -e "\033[36m#file\033[39m: ${{ inputs.file }}"
          echo -e "\033[36m#push\033[39m: ${{ inputs.push }}"
          echo -e "\033[36m#notify\033[39m: ${{ inputs.notify }}"
          echo -e "\033[36m#readme_path\033[39m: ${{ inputs.readme_path }}"
          echo -e "\033[36m#platforms\033[39m: ${{ inputs.platforms }}"
          echo -e "\033[36m#meta_labels\033[39m:\n${{ inputs.meta_labels }}"
          echo -e "\033[36m#annotations\033[39m:\n${{ inputs.annotations }}"

      - name: Prepare Vars
        uses: aliuq/script-action@v1.0.4-beta.2
        id: prepare
        with:
          script: |
            const images = (`${{ inputs.images }}`).split('\n')
            const platforms = (`${{ inputs.platforms }}`).split(',')

            const matchDockerhub = images.find(i => i.match(/^aliuq\//))
            const matchGhcr = images.find(i => i.match(/^ghcr.io\//))

            const repo = matchDockerhub ? matchDockerhub : matchGhcr ? matchGhcr?.replace(/^ghcr.io\//, '') : ''
            const app = matchDockerhub ? matchDockerhub.split('/')[1] : matchGhcr ? matchGhcr.split('/')[2] : ''

            outputJson({ 
              build_dockerhub: !!matchDockerhub, 
              build_ghcr: !!matchGhcr,
              has_platforms: platforms.length > 1,
              repo, app
            })

      - name: Docker meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ inputs.images }}
          tags: ${{ inputs.tags }}
          labels: ${{ inputs.meta_labels }}
          annotations: ${{ inputs.annotations }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: steps.prepare.outputs.build_dockerhub == 'true'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        if: steps.prepare.outputs.build_ghcr == 'true'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: steps.prepare.outputs.has_platforms == 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        id: build
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          platforms: ${{ inputs.platforms }}
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            ${{ inputs.labels }}

      - name: Sync README to DockerHub
        uses: peter-evans/dockerhub-description@v4
        if: inputs.readme_path != '' && inputs.push && steps.prepare.outputs.repo != '' && steps.prepare.outputs.build_dockerhub == 'true'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ steps.prepare.outputs.repo }}
          readme-filepath: ${{ inputs.readme_path }}

      - name: Post vars
        uses: aliuq/script-action@v1.0.4-beta.2
        id: post
        with:
          script: |
            const action_url = "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            const tags = (`${{ steps.meta.outputs.tags }}`).split('\n').map(t => `\`${t}\``).join('\n')
            const url = (`${{ inputs.meta_labels }}`).match(/org.opencontainers.image.url=(.*)/)?.[1] || ''

            const data = { tags, action_url }

            url && (data.url = url)
            if ("${{ steps.prepare.outputs.repo }}" !== '') {
              data.dockerhub_url = `https://hub.docker.com/r/${{ steps.prepare.outputs.repo }}`
            }
            if ("${{ steps.prepare.outputs.app }}" !== '') {
              data.ghcr_url = `https://github.com/users/aliuq/packages/container/package/${{ steps.prepare.outputs.app }}`
            }

            console.log(data)
            outputJson(data)

      - name: Send Telegram Notify
        uses: aliuq/telegram-action@v1
        if: env.BOT_TOKEN && env.CHAT_ID && inputs.push && inputs.notify
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        with:
          bot_token: ${{ secrets.BOT_TOKEN }}
          chat_id: ${{ secrets.CHAT_ID }}
          reply_to_message_id: ${{ secrets.REPLY_TO_MESSAGE_ID }}
          message: |
            🎉 [**${{ steps.prepare.outputs.repo }}**](${{ steps.post.outputs.url }}) has a new image

            ${{ steps.post.outputs.tags }}

            [**Action**](${{ steps.post.outputs.action_url }}) | [**Repo**](https://github.com/${{ github.repository }}) | [**DockerHub**](${{ steps.post.outputs.dockerhub_url }}) | [**GHCR**](${{ steps.post.outputs.ghcr_url }})

            #build_image_notify
